// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default Firebase configuration options for development environment.
///
/// This file should be generated using: flutterfire configure --project=hydracattest
///
/// For now, this is a placeholder that will be replaced by the actual generated config.
class DefaultFirebaseOptionsDev {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptionsDev have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptionsDev have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptionsDev are not supported for this platform.',
        );
    }
  }

  // Generated config from: flutterfire configure --project=hydracattest
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'your-api-key',
    appId: 'your-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'hydracattest',
    authDomain: 'hydracattest.firebaseapp.com',
    storageBucket: 'hydracattest.appspot.com',
    databaseURL: 'https://hydracattest-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuqcZhj5uhEBKzHQniOflF4zfneVDdsGY',
    appId: '1:248700006204:android:fec11b962bce1c0000b839',
    messagingSenderId: '248700006204',
    projectId: 'hydracattest',
    storageBucket: 'hydracattest.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyOpSFfWF-q9h0oVl0Heu6SZ3fHfanM7g',
    appId: '1:248700006204:ios:e49d2b8d44050c3b00b839',
    messagingSenderId: '248700006204',
    projectId: 'hydracattest',
    storageBucket: 'hydracattest.firebasestorage.app',
    iosBundleId: 'com.example.hydracatTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'your-api-key',
    appId: 'your-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'hydracattest',
    storageBucket: 'hydracattest.appspot.com',
    iosBundleId: 'com.example.hydracatTest',
  );
}
