// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default Firebase configuration options for production environment.
///
/// This file should be generated using: flutterfire configure --project=myckdapp
///
/// For now, this is a placeholder that will be replaced by the actual generated config.
class DefaultFirebaseOptionsProd {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptionsProd have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptionsProd have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptionsProd are not supported for this platform.',
        );
    }
  }

  // Generated config from production Firebase project: myckdapp
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiDgHlgPm43wqQpUOpRdBF2EQ-W-hPZRI',
    appId: '1:592563767500:web:1e31299d30698ccf9dda69',
    messagingSenderId: '592563767500',
    projectId: 'myckdapp',
    authDomain: 'myckdapp.firebaseapp.com',
    storageBucket: 'myckdapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiDgHlgPm43wqQpUOpRdBF2EQ-W-hPZRI',
    appId: '1:592563767500:android:1e31299d30698ccf9dda69',
    messagingSenderId: '592563767500',
    projectId: 'myckdapp',
    storageBucket: 'myckdapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASbJlQxrkUEjCy6VwzR5lO0nTrz1Rrxbs',
    appId: '1:592563767500:ios:9a052832453a3f9f9dda69',
    messagingSenderId: '592563767500',
    projectId: 'myckdapp',
    storageBucket: 'myckdapp.firebasestorage.app',
    iosBundleId: 'com.example.hydracat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASbJlQxrkUEjCy6VwzR5lO0nTrz1Rrxbs',
    appId: '1:592563767500:ios:9a052832453a3f9f9dda69',
    messagingSenderId: '592563767500',
    projectId: 'myckdapp',
    storageBucket: 'myckdapp.firebasestorage.app',
    iosBundleId: 'com.example.hydracat',
  );
}
